// app/layout.tsx
import type { Metadata } from "next";
import { Jost, Oxanium } from "next/font/google";


// Load fonts
const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-jost",
});

const oxanium = Oxanium({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-oxanium",
});

export const metadata: Metadata = {
  title: "Community",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${jost.variable} ${oxanium.variable}`}>
      <body className="antialiased font-jost">
        {children}
      </body>
    </html>
  );
}
