// app/layout.tsx
import type { Metadata } from "next";
import { Jost, Oxanium } from "next/font/google";

import { Navbar } from "./_components/MainComponent/Navbar";
import { Footer } from "./_components/MainComponent/Footer";

// Load fonts
const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-jost",
});



export const metadata: Metadata = {
  title: "Community",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${jost.variable} `} suppressHydrationWarning={true}>
      <body className="antialiased font-jost" suppressHydrationWarning={true}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
