import type { Metadata } from "next";
import { Jost,Oxanium} from "next/font/google";
import "./globals.css";


const jost = Jost({ subsets: ["latin"], weight: ["400", "700"] });
const oxanium = Oxanium({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Community",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.className} ${oxanium.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}